stages:
  - tag

cache:
  paths:
    - node_modules/

semantic_release:
  stage: tag
  image: node:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - npm install
  script:
    - npx semantic-release
  only:
    - master
