stages:
  - validate
  - version

validate:
  stage: validate
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .terraform
  before_script:
    - terraform init
  script:
    - terraform validate
    - terraform fmt -check=true
  only:
    - branches

version:
  stage: version
  cache:
    paths:
      - node_modules/
  image: node:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - npm install
  script:
    - npx semantic-release
  only:
    - master

