stages:
  - version

cache:
  paths:
    - node_modules/

version:
  stage: version
  image: node:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - npm install
  script:
    - npx semantic-release
  only:
    - master
